server:
  port: ${PORT:8085}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  elasticsearch:
    uris: ${ELASTICSEARCH_URL}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: scramblo-ai
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.scramblo.ai.dto.ArticlePublishedEvent

gemini:
  api:
    key: ${GEMINI_API_KEY}